UPPERCASE_CHECK_DIGITS = "TRWAGMYFPDXBNJZSQVHLCKE"
LOWERCASE_CHECK_DIGITS = UPPERCASE_CHECK_DIGITS.lower()
REGEX_FOR_UPPER_OR_LOWER_CHECK_DIGIT = (
    f"[{UPPERCASE_CHECK_DIGITS+LOWERCASE_CHECK_DIGITS}]{{1}}[a-zA-Z]*"
)
REGEX_FOR_8_DIGIT_NUMBER = "[^1-9]*([1-9]{8})[^1-9]*"
